#!/usr/bin/bash
ZPATH="$1";
if [ -d $ZPATH ]
then
	echo "Processing $ZPATH";
else
	ZPATH="./"
	echo "Processing $ZPATH";
fi
find $ZPATH
find ./ -name "*.pm" -exec "$TOOLBOXDIR/perl/script/selectivebump.pl" {} \; 