#!/bin/bash

#drop is default, sometimes we want the drop logged
in_port_logged_bl=()
in_host_logged_bl=()
#there is no legitimate reason to be ssh-ing out from a server, and i've been bitten by getting relay'd before
out_host_logged_bl=(22)
