#!/bin/bash
#EDIT THIS FILE FOR THE SYSTEM IN QUESTION!!!

SYSCTL="/sbin/sysctl -w"

### slackware
IPT="/usr/sbin/iptables"
IPTS="/usr/sbin/iptables-save" 
IPTR="/usr/sbin/iptables-restore"


init_chain(){
	echo "init_chain($1)"
	$IPT -F "$1" 2>/dev/null
	$IPT -X "$1" 2>/dev/null
	$IPT -N "$1"
	$IPT -I "$1" -j RETURN
}


### debian (?)
#IPT="/sbin/iptables"
#IPTS="/sbin/iptables-save"
#IPTR="/sbin/iptables-restore"

#Localhost Interface
LO_IFACE="lo" 
LO_IP="127.0.0.1"

#INTERNET INTERFACE
INET_IFACE="eth0"

